# -*- coding: utf-8 -*-
{
    'name': 'Multi-Company Inventory Transfer',

    'summary': 'This App serves the feature of maintaining inventory transactions between same or different companies.',

    'description': """
Internal Inventory Transfer Apps,
    Best inventory Transfer Apps,
    Inventory Transfer Apps,
    Direct Product Transfer Apps,
    Multi Product Transfer Apps,
    Multi Company Product Transfer Apps,
    Inter Company Product Transfer Apps,
    Product Transfer Apps,
    One Click Inventory Transfer Apps,
    Instant Product Transfer Apps,
    Multi Warehouse Transfer Apps,
    Internal Product Transfer Apps,
    Direct Inventory Transfer Apps,
    Best Inventory Transfer Apps,
    Product Transfer Apps,
    Inter Product Transfer Apps,
    Inter Inventory Transfer Apps,
    Easy Inventory Transfer Apps,
    Multi Location Warehouse Transfer,
    Instant Inventory Transfer Apps,
    Quick Product Transfer Apps,
    Fast inter Inventory Transfer Apps,
    Fast Inventory Apps,
    Immediate Inventory Transfer Apps,
    Easy Inventory Exchange,
    Inventory Transfer,
    Inter Company Product Transfer,
    Best Product Transfer Apps,
    Direct Inventory Transfer Apps,
    Inter Company Inventory Transfer Apps,
    Multi Warehouse Movement,
    Multi location Transfer Apps,
    Inter Warehouse Stock Transfer Apps,
    Quick Stock Transfer,
    Fast Stock Transfer,
    Instant Stock Transfer,
    Immediate Stock Transfer ,
    Immediate Product Transfer,
    Instant Inventory Transfer,
    Odoo Inventory Internal Transfer
    """,

    'author': "Ksolves India Ltd.",
    'license': 'OPL-1',
    'currency': 'EUR',
    'live_test_url': 'https://multicompany-transfer18.kappso.com/',
    'price': 49.00,
    'website': 'https://www.ksolves.com/',
    'maintainer': 'Ksolves India Pvt. Ltd.',
    'version': '18.0.1.0.0',
    'category': 'Warehouse',
    'support': 'sales@ksolves.com',
    'depends': ['base', 'stock', 'account', 'stock_account'],
    'data': [
        'data/ks_sequence.xml',
        'security/ks_security.xml',
        'security/ir.model.access.csv',
        'view/ks_multi_company_inventory.xml',
        'view/product_category_views.xml',
        'view/res_users_views.xml',
    ],
    'images': ['static/description/v18_inven.png'],
    'installable': True,
    'application': True,
}
