from . import sale_order_line
from . import account_move_line
from . import account_move
from . import product_template
from . import product_category
from . import res_users
from . import res_config_settings
from . import sale_order
from . import stock_details_wizard
from . import res_partner
from . import res_company
from . import stock_move
from . import account_payment
from . import purchase_order
from . import purchase_order2
from . import account_move2
from . import account_move_analysis
from . import account_move_zero_quantities_wizard
from . import stock_picking
from . import stock_picking_zero_quantities_wizard

